---
- name: Configure Web Servers
  hosts: all
  become: yes
  vars_files:
    - roles/webserver/vars/secrets.yml  # Load the encrypted data
  roles:
    - common      # Runs first to prep the OS
    - webserver