$ANSIBLE_VAULT;1.1;AES256
36303865633931396132346634353538386130393565663731373065303733323832386161643666
6231643862393433643630363038633034343237633336370a343862306164356432643632646230
64383430336465306634346239656261633134623136396338313138653334363063653038363834
6537383735623931630a356164313632623837646162616230653364343732656235393433393830
64363533326364366333336133666166626162666336303931656265356334306631
