$ANSIBLE_VAULT;1.1;AES256
30383534323434343535633730616435343835396233323836363635356332393661626362653464
3263333938366363333931323065626237616361623163340a633738326535643330396637353739
64316361626137663863613738626335306265333164666630303561343664666537346337313337
3336383166613832320a336438613938323466366161323136323962376364303036316533373432
33366637646336383234316237386538313665316564386163396132623632393330313165396462
35646433336634363430646564326261306433663134383063323137346638323435626538333635
32346439323764623737333031346162396230303966383864373030656432616262303134343166
62633261383965323436
