name: Packer Build Golden AMI

on:
  push:
    branches:
      - main
    paths:
      - '03-infrastructure-as-code/projects/golden-ami-pipeline/**'
  #Added: Allows you to trigger the build manually from the GitHub Actions tab
  workflow_dispatch:

jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # This tells GitHub to ignore those nested .git folders
          submodules: false 
          fetch-depth: 1

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      # We create the password file in the root for maximum reliability
      - name: Create Ansible Vault Password File
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .ansible_vault_pass

      - name: Verify Vault Password File
        run: |
          if [ ! -s .ansible_vault_pass ]; then
            echo "Error: Vault password file is empty or missing!"
            exit 1
          fi

      - name: Packer Init
        run: packer init .
        working-directory: 03-infrastructure-as-code/projects/golden-ami-pipeline/packer

      - name: Packer Build
        run: |
          packer build \
          -var "vault_password_file=$GITHUB_WORKSPACE/.ansible_vault_pass" \
          -var "playbook_file_path=$GITHUB_WORKSPACE/03-infrastructure-as-code/projects/golden-ami-pipeline/ansible/site.yml" \
          -var "ansible_roles_path=$GITHUB_WORKSPACE/03-infrastructure-as-code/projects/golden-ami-pipeline/ansible/roles" \
          .
        working-directory: 03-infrastructure-as-code/projects/golden-ami-pipeline/packer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          AWS_REGION: "us-east-1"
          ANSIBLE_ROLES_PATH: "03-infrastructure-as-code/projects/golden-ami-pipeline/ansible/roles"
          