name: Packer Build Golden AMI

on:
  push:
    branches:
      - main

jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures git has full history to avoid exit code 128

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      # This creates the vault file in the exact folder where Packer runs
      - name: Create Ansible Vault Password File
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > 03-infrastructure-as-code/projects/golden-ami-pipeline/packer/.ansible_vault_pass

      - name: Packer Init
        run: packer init .
        working-directory: 03-infrastructure-as-code/projects/golden-ami-pipeline/packer

      - name: Packer Build
        run: packer build .
        working-directory: 03-infrastructure-as-code/projects/golden-ami-pipeline/packer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          AWS_REGION: "us-east-1"