name: Push to Docker Hub

on:
  push:
    branches: [ "main" ]
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Stack
        run: |
          # Create dummy .env
          echo "DB_USER=test_user" >> .env
          echo "DB_PASSWORD=test_pass" >> .env
          echo "DATABASE_URL=mongodb://test_user:test_pass@db:27017/test_db?authSource=admin" >> .env
          
          # Use --build to ensure it uses the code in the repo
          docker compose up -d --build 
        working-directory: ./04-containerization/code-labs/docker-compose/three-tier-app-configuration

      - name: Check Container Status
        run: docker ps

      - name: Check Backend Application Logs
        run: |
          sleep 10 # Give the app a few seconds to finish the handshake
          docker compose logs backend
        working-directory: ./04-containerization/code-labs/docker-compose/three-tier-app-configuration

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          # This is the folder where your code lives
          context: ./04-containerization/code-labs/docker-compose/three-tier-app-configuration/backend
          # This tells Docker exactly where the Dockerfile is inside that folder
          file: ./04-containerization/code-labs/docker-compose/three-tier-app-configuration/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fiddly-backend:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./04-containerization/code-labs/docker-compose/three-tier-app-configuration/frontend
          file: ./04-containerization/code-labs/docker-compose/three-tier-app-configuration/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fiddly-frontend:latest

      - name: Verify Backend Handshake
        run: |
          sleep 15
          docker compose logs backend | grep "Connected to MongoDB"
        working-directory: ./04-containerization/code-labs/docker-compose/three-tier-app-configuration