name: Push to Docker Hub

on:
  push:
    branches: [ "main" ]
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Stack
        run: |
          # Create dummy .env
          echo "DB_USER=test_user" >> .env
          echo "DB_PASSWORD=test_pass" >> .env
          echo "DATABASE_URL=mongodb://test_user:test_pass@db:27017/test_db?authSource=admin" >> .env
          
          # Use --build to ensure it uses the code in the repo
          docker compose up -d --build 
        working-directory: ./04-containerization/code-labs/docker-compose/three-tier-app-configuration

      - name: Check Container Status
        run: docker ps

      - name: Check Backend Application Logs
        run: |
          sleep 10 # Give the app a few seconds to finish the handshake
          docker compose logs backend
        working-directory: ./04-containerization/code-labs/docker-compose/three-tier-app-configuration

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./04-containerization/code-labs/docker-compose/three-tier-app-configuration/backend
          file: ./04-containerization/code-labs/docker-compose/three-tier-app-configuration/backend/Dockerfile
          push: true
          tags: |
            nikkytechies/fiddly-backend:latest
            nikkytechies/fiddly-backend:v${{ github.run_number }}
            nikkytechies/fiddly-backend:${{ github.sha }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./04-containerization/code-labs/docker-compose/three-tier-app-configuration/frontend
          file: ./04-containerization/code-labs/docker-compose/three-tier-app-configuration/frontend/Dockerfile
          push: true
          tags: |
            nikkytechies/fiddly-frontend:latest
            nikkytechies/fiddly-frontend:v${{ github.run_number }}
            nikkytechies/fiddly-frontend:${{ github.sha }}
      - name: Verify Handshake
        run: |
          sleep 20
          # We check ALL logs to see if there is a connection error
          docker compose logs
          # This line will still fail the build if the message isn't there
          docker compose logs | grep "Connected to MongoDB"
        working-directory: ./04-containerization/code-labs/docker-compose/three-tier-app-configuration